config/routes.rb
Rails.application.routes.draw do

  resources :ideas

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get "/home" => "home#index"
  get "/ideas" => "ideas#index"

  root "home#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :email,      presence: true, uniqueness: true, format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

  def sign_in(user)
    session[:user_id] = user.id
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def new
    @idea = Idea.new
  end

  def create
    idea_params = params.require(:idea).permit(:title, :body)
    idea = Idea.new idea_params
    idea.user = current_user
    if idea.save
      redirect_to idea_path(idea), notice: "Eureka! Your Idea Was Submitted."
    else
      render :new
    end
  end

  def show
    @idea = Idea.find params[:id]
  end

  def index
    @ideas = Idea.all
  end

  def edit
    @idea = Idea.find params[:id]
  end

  def update
    idea_params = params.require(:idea).permit(:title, :body)
    idea = Idea.find params[:id]
    if idea.update idea_params
      redirect_to idea_path(idea), notice: "Idea Updated"
    else
      render :edit
    end
  end

  def destroy
    idea = Idea.find params[:id]
    idea.destroy
    redirect_to ideas_path, notice: "Idea Deleted"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to home_path, notice: "Signed In!"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Signed Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to home_path, notice: "Account Created!"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 align="center">Welcome to Idea Factory!</h1>
<%= image_tag "idea.jpg", width: "100%" %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @idea do |i| %>
<div>
  <%= i.label :title %>
  <%= i.text_field :title %>
</div>
<div>
  <%= i.label :body %>
  <%= i.text_area :body %>
</div>
<%= i.submit %>
<% end %>

app/views/ideas/index.html.erb
<h1>Ideas Index</h1>
<hr>
<% @ideas.each do |idea| %>
  <div>
    <h3><%= link_to idea.title, idea_path(idea) %></h3>
    <p><%= idea.body %></p>
    <p>By <%= idea.user.full_name.titleize %></p>
  </div>
  <hr>
<% end %>

app/views/ideas/new.html.erb
<h1>Submit New Idea</h1>

<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @idea do |i| %>
<div>
  <%= i.label :title %>
  <%= i.text_field :title %>
</div>
<div>
  <%= i.label :body %>
  <%= i.text_area :body %>
</div>
<%= i.submit %>
<% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p><%= @idea.body %></p>
<p>Idea by <%= @idea.user.full_name.titleize %></p>
<p><%= @idea.created_at %></p>

<%= link_to "Edit", edit_idea_path(@idea) %>
<%= link_to "Delete", idea_path(@idea), method: :delete, data: {confirm: "Are you sure you want to delete this idea?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaFactory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p style="text-align:left;">
    <%= link_to "Home", home_path %>
    <%= link_to "Ideas", ideas_path %>
    <%= link_to "New Idea", new_idea_path %>
    <span style="float:right;">
      <% if user_signed_in? %>
      Hello <%= current_user.full_name %>!
      <%= link_to "Sign Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to sign out?"}%>
      <% else %>
      <%= link_to "Sign In", new_session_path%>
      <%= link_to "Create Account", new_user_path%>
      <% end %>
    </span>
  </p>

<%= flash[:notice] || flash[:alert] %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create Account</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |u| %>
  <div>
    <%= u.label :first_name %>
    <%= u.text_field :first_name %>
  </div>
  <div>
    <%= u.label :last_name %>
    <%= u.text_field :last_name %>
  </div>
  <div>
    <%= u.label :email %>
    <%= u.email_field :email %>
  </div>
  <div>
    <%= u.label :password %>
    <%= u.password_field :password %>
  </div>
  <div>
    <%= u.label :password_confirmation %>
    <%= u.password_field :password_confirmation %>
  </div>
  <%= u.submit %>
<% end %>